// Generated by imboy/scripts/generate_product_features.py; do not edit.
import 'package:flutter/cupertino.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:imboy/page/channel/channel_detail_page.dart';
import 'package:imboy/page/channel/channel_list_page.dart';
import 'package:imboy/page/conversation/subscribed_channel_strip_provider.dart';
import 'package:imboy/page/conversation/widget/subscribed_channel_strip.dart';
import 'routes/channel_routes.dart';
import 'routes/channel_discover_routes.dart';
import 'routes/channel_invitation_routes.dart';
import 'routes/channel_order_routes.dart';

const productFeatureRouteManifestHash =
    "sha256:742ac6339a119cadb6d191166f2fdea5dfcc9f3714034b152a80f6f23d820668";
const productFeatureRouteSchemaVersion = 1;
const productFeatureRouteFeatures = <String>[
  "bot_webhook",
  "channel",
  "channel_discover",
  "channel_invitation",
  "channel_order",
  "core",
  "e2ee",
];

List<RouteBase> compiledProductFeatureRoutes() => <RouteBase>[
  ...channelRoutes(
    featureRoutes: <RouteBase>[
      ...channelDiscoverRoutes(),
      ...channelInvitationRoutes(),
      ...channelOrderRoutes(),
    ],
  ),
];

Widget? compiledChannelListPage() => const ChannelListPage();
Widget? compiledChannelDetailPage(String channelId) =>
    ChannelDetailPage(channelId: channelId, autoLoadStats: false);
Widget? compiledSubscribedChannelStrip() => const SubscribedChannelStrip();
int compiledChannelUnreadCount(WidgetRef ref) =>
    ref
        .watch(subscribedChannelStripProvider)
        .value
        ?.fold<int>(
          0,
          (sum, item) => item.isMuted ? sum : sum + item.unreadCount,
        ) ??
    0;
