/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package flutter.imboy;

import org.gradle.testfixtures.ProjectBuilder;
import org.gradle.api.Project;
import org.junit.Test;
import static org.junit.Assert.*;

/**
 * A simple unit test for the 'flutter.imboy.greeting' plugin.
 */
public class FlutterImboyPluginTest {
    @Test public void pluginRegistersATask() {
        // Create a test project and apply the plugin
        Project project = ProjectBuilder.builder().build();
        project.getPlugins().apply("flutter.imboy.greeting");

        // Verify the result
        assertNotNull(project.getTasks().findByName("greeting"));
    }
}
