sdk.dir=/Users/leeyi/Library/Android/sdk
flutter.sdk=/Users/leeyi/dev/flutter
flutter.compileSdkVersion=35
flutter.buildMode=release
flutter.versionName=0.6.1
flutter.ndkVersion=28.2.13676358
jpush.appKey=
jpush.masterSecret=
keyAlias=upload
storePassword=
keyPassword=
huawei.appId=
storeFile=
