// Generated by imboy/scripts/generate_product_features.py; do not edit.
import 'package:flutter/widgets.dart';
import 'package:imboy/page/channel/paid/channel_paywall_view.dart';
import 'package:imboy/store/model/channel_model.dart';

const channelOrderWidgetManifestHash =
    "sha256:b59aae27976015823e315e9a5ee42bb2af3970cec92c97df04b517b4674d1457";
const channelOrderWidgetSchemaVersion = 1;
const channelOrderWidgetFeatures = <String>[
  "channel",
  "channel_discover",
  "channel_invitation",
  "channel_order",
  "core",
  "e2ee",
  "group_schedule",
  "group_task",
  "group_vote",
  "location",
  "moment",
];

Widget? compiledChannelPaywall({
  required ChannelModel channel,
  required VoidCallback onPurchased,
}) => ChannelPaywallView(channel: channel, onPurchased: onPurchased);
