// Generated by imboy/scripts/generate_product_features.py; do not edit.
import 'package:flutter/widgets.dart';
import 'package:imboy/page/channel/paid/channel_paywall_view.dart';
import 'package:imboy/store/model/channel_model.dart';

const channelOrderWidgetManifestHash =
    "sha256:b6f00f4cd9f203a82c8cb63e4d0f95b1dd843e647e0c4cafe3b5af49bb4e39d9";
const channelOrderWidgetSchemaVersion = 1;
const channelOrderWidgetFeatures = <String>[
  "bot_webhook",
  "channel",
  "channel_discover",
  "channel_invitation",
  "channel_order",
  "core",
  "e2ee",
  "group_schedule",
  "group_task",
  "group_vote",
  "location",
  "moment",
];

Widget? compiledChannelPaywall({
  required ChannelModel channel,
  required VoidCallback onPurchased,
}) => ChannelPaywallView(channel: channel, onPurchased: onPurchased);
