// Generated by imboy/scripts/generate_product_features.py; do not edit.
const productFeatureSchemaVersion = 1;
const productFeatureManifestHash =
    "sha256:742ac6339a119cadb6d191166f2fdea5dfcc9f3714034b152a80f6f23d820668";
const compiledProductFeatures = <String>[
  "bot_webhook",
  "channel",
  "channel_discover",
  "channel_invitation",
  "channel_order",
  "core",
  "e2ee",
];
