// Generated by imboy/scripts/generate_product_features.py; do not edit.
const productFeatureSchemaVersion = 1;
const productFeatureManifestHash =
    "sha256:b59aae27976015823e315e9a5ee42bb2af3970cec92c97df04b517b4674d1457";
const compiledProductFeatures = <String>[
  "channel",
  "channel_discover",
  "channel_invitation",
  "channel_order",
  "core",
  "e2ee",
  "group_schedule",
  "group_task",
  "group_vote",
  "location",
  "moment",
];
