// Generated by imboy/scripts/generate_product_features.py; do not edit.
import 'package:flutter/widgets.dart';
import 'package:imboy/page/channel/paid/channel_paywall_view.dart';
import 'package:imboy/store/model/channel_model.dart';

const channelOrderWidgetManifestHash =
    "sha256:742ac6339a119cadb6d191166f2fdea5dfcc9f3714034b152a80f6f23d820668";
const channelOrderWidgetSchemaVersion = 1;
const channelOrderWidgetFeatures = <String>[
  "bot_webhook",
  "channel",
  "channel_discover",
  "channel_invitation",
  "channel_order",
  "core",
  "e2ee",
];

Widget? compiledChannelPaywall({
  required ChannelModel channel,
  required VoidCallback onPurchased,
}) => ChannelPaywallView(channel: channel, onPurchased: onPurchased);
